### ISSUE TITLE
Setting ansible_python_interpreter to "python3" breaks on RHEL7/SELinux

### ISSUE THREAD

**Issue by direvus** [alvistack/ansible-role-crowd#1]
Hi there @hswong3i, today I bumped into a problem running the latest version of this role against RHEL7 nodes with SELinux enabled.

The playbook failed on the task "download archive", and the error message was:

```
Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
```

The normal fix for this problem is to install the selinux bindings package for python3, but RHEL7 has no such package currently, and it's unclear whether it will get one any time soon. [1]

I was able to get the role to run successfully on my system, by removing the vars override for ansible_python_interpreter from the "download archive" task.  Perhaps we need to make this setting conditional based on the distro, or even run some kind of test to see whether python3 is safe to use an the ansible interpreter?

Thanks,
Brendan

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1756015

**Comment by hswong3i** [comment]
Please check https://github.com/alvistack/ansible-role-crowd/blob/master/molecule/default/converge.yml

You will found that I run my `python` role before `crowd` role: this is because **A LOT OF** different combination and matrix between Python3 and CentOS/RHEL/openSUSE and so finally I give up on solving those issue(s) one-by-one, but simply putting them altogether into `python` role... Afterward, always enforce the use of Python3 by `ansible_python_interpreter` on-the-fly during tasks if required.

Trust me, you won't like to debug those Python3 issues, just simply apply my `python` role ASAP during your play ;-)
